## Checks file generated by shell script to make sure all ids are present

with open('allnames', 'r') as mintnames:
    nft_names = mintnames.readlines()

# Parses file name and converts to int
nft_names = [ int(k.split(' ')[1].replace('"\n', '')) for k in nft_names]
nft_names.sort()

# Check for missing numbers
for i in range(729):
    if i not in nft_names:
        print(i)

